package innovimax.quixproc.datamodel;

public enum QuiXToken {
	// Here is the grammar of events
	// sequence := START_SEQUENCE, document*, END_SEQUENCE
	// document := START_DOCUMENT, (PROCESSING-INSTRUCTION|COMMENT)*, element,
	// (PROCESSING-INSTRUCTION|COMMENT)*, END_DOCUMENT
	// element := START_ELEMENT, (NAMESPACE|ATTRIBUTE)*,
	// (TEXT|element|PROCESSING-INSTRUCTION|COMMENT)*, END_ELEMENT

	START_SEQUENCE, END_SEQUENCE, START_DOCUMENT, END_DOCUMENT, NAMESPACE, START_ELEMENT, END_ELEMENT, ATTRIBUTE, TEXT, PI, COMMENT
}